default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= (ENV["RAILS_MAX_THREADS"] || 5).to_i %>
  host:     <%= ENV["DATABASE_HOST"] || "localhost" %>
  username: <%= ENV["DATABASE_USER"] || "pguser" %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: Northwind_development

test:
  <<: *default
  database: Northwind_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
